version: "3.8"

services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bot_container
    environment:
      - BOT_TOKEN=YOUR_BOT_TOKEN
      - POSTGRES_DB_URL=postgresql+asyncpg://postgres:postgres@postgres:5432/postgres
    depends_on:
      - postgres

  postgres:
    image: postgres:16
    container_name: db_container
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - pg_data:/var/lib/postgresql/data
  
volumes:
  pg_data:
